{
  "ansible_facts": {
    "ansible_all_ipv4_addresses": [
      "10.4.11.195",
      "10.0.10.201"
    ],
    "ansible_all_ipv6_addresses": [
      "fe80::974c:10ec:a6b5:2ab7",
      "fe80::ccef:1f23:7dbb:8288"
    ],
    "ansible_apparmor": {
      "status": "disabled"
    },
    "ansible_architecture": "x86_64",
    "ansible_bios_date": "01/03/2019",
    "ansible_bios_vendor": "HP",
    "ansible_bios_version": "Q78 Ver. 01.06.00",
    "ansible_board_asset_tag": "NA",
    "ansible_board_name": "83B2",
    "ansible_board_serial": "NA",
    "ansible_board_vendor": "HP",
    "ansible_board_version": "KBC Version 04.57.00",
    "ansible_chassis_asset_tag": "NA",
    "ansible_chassis_serial": "NA",
    "ansible_chassis_vendor": "HP",
    "ansible_chassis_version": "NA",
    "ansible_cmdline": {
      "BOOT_IMAGE": "(hd0,gpt2)/vmlinuz-6.3.12-100.fc37.x86_64",
      "quiet": true,
      "rd.luks.uuid": "luks-3ba07c47-486c-4025-bdbf-f40723721bf2",
      "rhgb": true,
      "ro": true,
      "root": "UUID=531f9d46-9f89-4571-b784-ace6e0f33d93",
      "rootflags": "subvol=thai23"
    },
    "ansible_date_time": {
      "date": "2023-07-23",
      "day": "23",
      "epoch": "1690098245",
      "epoch_int": "1690098245",
      "hour": "09",
      "iso8601": "2023-07-23T07:44:05Z",
      "iso8601_basic": "20230723T094405021315",
      "iso8601_basic_short": "20230723T094405",
      "iso8601_micro": "2023-07-23T07:44:05.021315Z",
      "minute": "44",
      "month": "07",
      "second": "05",
      "time": "09:44:05",
      "tz": "CEST",
      "tz_dst": "CEST",
      "tz_offset": "+0200",
      "weekday": "Sunday",
      "weekday_number": "0",
      "weeknumber": "29",
      "year": "2023"
    },
    "ansible_default_ipv4": {
      "address": "10.4.11.195",
      "alias": "tun0",
      "broadcast": "",
      "gateway": "10.4.11.1",
      "interface": "tun0",
      "macaddress": "",
      "mtu": 1419,
      "netmask": "255.255.255.0",
      "network": "10.4.11.0",
      "prefix": "24",
      "type": "tunnel"
    },
    "ansible_default_ipv6": {
      "address": "fe80::974c:10ec:a6b5:2ab7",
      "interface": "tun0",
      "macaddress": "",
      "mtu": 1419,
      "prefix": "64",
      "scope": "link",
      "type": "tunnel"
    },
    "ansible_device_links": {
      "ids": {
        "dm-0": [
          "dm-name-luks-3ba07c47-486c-4025-bdbf-f40723721bf2",
          "dm-uuid-CRYPT-LUKS2-3ba07c47486c4025bdbff40723721bf2-luks-3ba07c47-486c-4025-bdbf-f40723721bf2"
        ],
        "nvme0n1": [
          "nvme-SAMSUNG_MZVLB512HAJQ-000H1_S3WTNY0K906377",
          "nvme-eui.002538898102cce2"
        ],
        "nvme0n1p1": [
          "nvme-SAMSUNG_MZVLB512HAJQ-000H1_S3WTNY0K906377-part1",
          "nvme-eui.002538898102cce2-part1"
        ],
        "nvme0n1p2": [
          "nvme-SAMSUNG_MZVLB512HAJQ-000H1_S3WTNY0K906377-part2",
          "nvme-eui.002538898102cce2-part2"
        ],
        "nvme0n1p3": [
          "nvme-SAMSUNG_MZVLB512HAJQ-000H1_S3WTNY0K906377-part3",
          "nvme-eui.002538898102cce2-part3"
        ]
      },
      "labels": {
        "dm-0": [
          "fedora_localhost-live"
        ]
      },
      "masters": {
        "nvme0n1p3": [
          "dm-0"
        ]
      },
      "uuids": {
        "dm-0": [
          "531f9d46-9f89-4571-b784-ace6e0f33d93"
        ],
        "nvme0n1p1": [
          "5893-682A"
        ],
        "nvme0n1p2": [
          "a60aec6f-6155-4d6a-bfed-55731f4fbef9"
        ],
        "nvme0n1p3": [
          "3ba07c47-486c-4025-bdbf-f40723721bf2"
        ]
      }
    },
    "ansible_devices": {
      "dm-0": {
        "holders": [],
        "host": "",
        "links": {
          "ids": [
            "dm-name-luks-3ba07c47-486c-4025-bdbf-f40723721bf2",
            "dm-uuid-CRYPT-LUKS2-3ba07c47486c4025bdbff40723721bf2-luks-3ba07c47-486c-4025-bdbf-f40723721bf2"
          ],
          "labels": [
            "fedora_localhost-live"
          ],
          "masters": [],
          "uuids": [
            "531f9d46-9f89-4571-b784-ace6e0f33d93"
          ]
        },
        "model": null,
        "partitions": {},
        "removable": "0",
        "rotational": "0",
        "sas_address": null,
        "sas_device_handle": null,
        "scheduler_mode": "",
        "sectors": "996853760",
        "sectorsize": "512",
        "size": "475.34 GB",
        "support_discard": "0",
        "vendor": null,
        "virtual": 1
      },
      "nvme0n1": {
        "holders": [],
        "host": "Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller SM981/PM981/PM983",
        "links": {
          "ids": [
            "nvme-SAMSUNG_MZVLB512HAJQ-000H1_S3WTNY0K906377",
            "nvme-eui.002538898102cce2"
          ],
          "labels": [],
          "masters": [],
          "uuids": []
        },
        "model": "SAMSUNG MZVLB512HAJQ-000H1",
        "partitions": {
          "nvme0n1p1": {
            "holders": [],
            "links": {
              "ids": [
                "nvme-SAMSUNG_MZVLB512HAJQ-000H1_S3WTNY0K906377-part1",
                "nvme-eui.002538898102cce2-part1"
              ],
              "labels": [],
              "masters": [],
              "uuids": [
                "5893-682A"
              ]
            },
            "sectors": "1228800",
            "sectorsize": 512,
            "size": "600.00 MB",
            "start": "2048",
            "uuid": "5893-682A"
          },
          "nvme0n1p2": {
            "holders": [],
            "links": {
              "ids": [
                "nvme-SAMSUNG_MZVLB512HAJQ-000H1_S3WTNY0K906377-part2",
                "nvme-eui.002538898102cce2-part2"
              ],
              "labels": [],
              "masters": [],
              "uuids": [
                "a60aec6f-6155-4d6a-bfed-55731f4fbef9"
              ]
            },
            "sectors": "2097152",
            "sectorsize": 512,
            "size": "1.00 GB",
            "start": "1230848",
            "uuid": "a60aec6f-6155-4d6a-bfed-55731f4fbef9"
          },
          "nvme0n1p3": {
            "holders": [
              "luks-3ba07c47-486c-4025-bdbf-f40723721bf2"
            ],
            "links": {
              "ids": [
                "nvme-SAMSUNG_MZVLB512HAJQ-000H1_S3WTNY0K906377-part3",
                "nvme-eui.002538898102cce2-part3"
              ],
              "labels": [],
              "masters": [
                "dm-0"
              ],
              "uuids": [
                "3ba07c47-486c-4025-bdbf-f40723721bf2"
              ]
            },
            "sectors": "996886528",
            "sectorsize": 512,
            "size": "475.35 GB",
            "start": "3328000",
            "uuid": "3ba07c47-486c-4025-bdbf-f40723721bf2"
          }
        },
        "removable": "0",
        "rotational": "0",
        "sas_address": null,
        "sas_device_handle": null,
        "scheduler_mode": "none",
        "sectors": "1000215216",
        "sectorsize": "512",
        "serial": "S3WTNY0K906377",
        "size": "476.94 GB",
        "support_discard": "512",
        "vendor": null,
        "virtual": 1
      },
      "zram0": {
        "holders": [],
        "host": "",
        "links": {
          "ids": [],
          "labels": [],
          "masters": [],
          "uuids": []
        },
        "model": null,
        "partitions": {},
        "removable": "0",
        "rotational": "0",
        "sas_address": null,
        "sas_device_handle": null,
        "scheduler_mode": "",
        "sectors": "16777216",
        "sectorsize": "4096",
        "size": "8.00 GB",
        "support_discard": "4096",
        "vendor": null,
        "virtual": 1
      }
    },
    "ansible_distribution": "Fedora",
    "ansible_distribution_file_parsed": true,
    "ansible_distribution_file_path": "/etc/redhat-release",
    "ansible_distribution_file_variety": "RedHat",
    "ansible_distribution_major_version": "37",
    "ansible_distribution_release": "",
    "ansible_distribution_version": "37",
    "ansible_dns": {
      "nameservers": [
        "10.0.0.241"
      ]
    },
    "ansible_domain": "local",
    "ansible_effective_group_id": 1000,
    "ansible_effective_user_id": 1000,
    "ansible_enp0s31f6": {
      "active": false,
      "device": "enp0s31f6",
      "features": {
        "esp_hw_offload": "off [fixed]",
        "esp_tx_csum_hw_offload": "off [fixed]",
        "fcoe_mtu": "off [fixed]",
        "generic_receive_offload": "on",
        "generic_segmentation_offload": "on",
        "highdma": "on [fixed]",
        "hsr_dup_offload": "off [fixed]",
        "hsr_fwd_offload": "off [fixed]",
        "hsr_tag_ins_offload": "off [fixed]",
        "hsr_tag_rm_offload": "off [fixed]",
        "hw_tc_offload": "off [fixed]",
        "l2_fwd_offload": "off [fixed]",
        "large_receive_offload": "off [fixed]",
        "loopback": "off [fixed]",
        "macsec_hw_offload": "off [fixed]",
        "netns_local": "off [fixed]",
        "ntuple_filters": "off [fixed]",
        "receive_hashing": "on",
        "rx_all": "off",
        "rx_checksumming": "on",
        "rx_fcs": "off",
        "rx_gro_hw": "off [fixed]",
        "rx_gro_list": "off",
        "rx_udp_gro_forwarding": "off",
        "rx_udp_tunnel_port_offload": "off [fixed]",
        "rx_vlan_filter": "off [fixed]",
        "rx_vlan_offload": "on",
        "rx_vlan_stag_filter": "off [fixed]",
        "rx_vlan_stag_hw_parse": "off [fixed]",
        "scatter_gather": "on",
        "tcp_segmentation_offload": "off",
        "tls_hw_record": "off [fixed]",
        "tls_hw_rx_offload": "off [fixed]",
        "tls_hw_tx_offload": "off [fixed]",
        "tx_checksum_fcoe_crc": "off [fixed]",
        "tx_checksum_ip_generic": "on",
        "tx_checksum_ipv4": "off [fixed]",
        "tx_checksum_ipv6": "off [fixed]",
        "tx_checksum_sctp": "off [fixed]",
        "tx_checksumming": "on",
        "tx_esp_segmentation": "off [fixed]",
        "tx_fcoe_segmentation": "off [fixed]",
        "tx_gre_csum_segmentation": "off [fixed]",
        "tx_gre_segmentation": "off [fixed]",
        "tx_gso_list": "off [fixed]",
        "tx_gso_partial": "off [fixed]",
        "tx_gso_robust": "off [fixed]",
        "tx_ipxip4_segmentation": "off [fixed]",
        "tx_ipxip6_segmentation": "off [fixed]",
        "tx_lockless": "off [fixed]",
        "tx_nocache_copy": "off",
        "tx_scatter_gather": "on",
        "tx_scatter_gather_fraglist": "off [fixed]",
        "tx_sctp_segmentation": "off [fixed]",
        "tx_tcp6_segmentation": "off [fixed]",
        "tx_tcp_ecn_segmentation": "off [fixed]",
        "tx_tcp_mangleid_segmentation": "off [fixed]",
        "tx_tcp_segmentation": "off [fixed]",
        "tx_tunnel_remcsum_segmentation": "off [fixed]",
        "tx_udp_segmentation": "off [fixed]",
        "tx_udp_tnl_csum_segmentation": "off [fixed]",
        "tx_udp_tnl_segmentation": "off [fixed]",
        "tx_vlan_offload": "on",
        "tx_vlan_stag_hw_insert": "off [fixed]",
        "vlan_challenged": "off [fixed]"
      },
      "hw_timestamp_filters": [],
      "macaddress": "f4:39:09:e5:a7:09",
      "module": "e1000e",
      "mtu": 1500,
      "pciid": "0000:00:1f.6",
      "phc_index": 0,
      "promisc": false,
      "speed": -1,
      "timestamping": [],
      "type": "ether"
    },
    "ansible_env": {
      "ALACRITTY_LOG": "/tmp/Alacritty-6708.log",
      "ALACRITTY_SOCKET": "/run/user/1000/Alacritty-:1-6708.sock",
      "ALACRITTY_WINDOW_ID": "67108868",
      "BROWSER": "firefox",
      "COLORTERM": "truecolor",
      "DBUS_SESSION_BUS_ADDRESS": "unix:path=/run/user/1000/bus",
      "DEBUGINFOD_URLS": "https://debuginfod.fedoraproject.org/ ",
      "DESKTOP_SESSION": "gnome",
      "DISPLAY": ":0",
      "EDITOR": "emacsclient",
      "GDMSESSION": "gnome",
      "GDM_LANG": "en_US.UTF-8",
      "GIO_LAUNCHED_DESKTOP_FILE": "/usr/share/applications/Alacritty.desktop",
      "GIO_LAUNCHED_DESKTOP_FILE_PID": "6708",
      "GJS_DEBUG_OUTPUT": "stderr",
      "GJS_DEBUG_TOPICS": "JS ERROR;JS LOG",
      "GUESTFISH_INIT": "\\e[1;34m",
      "GUESTFISH_OUTPUT": "\\e[0m",
      "GUESTFISH_PS1": "\\[\\e[1;32m\\]><fs>\\[\\e[0;31m\\] ",
      "GUESTFISH_RESTORE": "\\e[0m",
      "HISTCONTROL": "ignoredups",
      "HISTSIZE": "1000",
      "HOME": "/home/gepr",
      "HOSTNAME": "g5",
      "INVOCATION_ID": "73a870bc8ee643638b59ba87a5fc52e9",
      "JOURNAL_STREAM": "8:40482",
      "LANG": "en_US.UTF-8",
      "LESSOPEN": "||/usr/bin/lesspipe.sh %s",
      "LOGNAME": "gepr",
      "LS_COLORS": "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=00:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.avif=01;35:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:*~=00;90:*#=00;90:*.bak=00;90:*.old=00;90:*.orig=00;90:*.part=00;90:*.rej=00;90:*.swp=00;90:*.tmp=00;90:*.dpkg-dist=00;90:*.dpkg-old=00;90:*.ucf-dist=00;90:*.ucf-new=00;90:*.ucf-old=00;90:*.rpmnew=00;90:*.rpmorig=00;90:*.rpmsave=00;90:",
      "MAIL": "/var/spool/mail/gepr",
      "MANAGERPID": "5085",
      "MOZ_GMP_PATH": "/usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed",
      "NO_AT_BRIDGE": "1",
      "OLDPWD": "/home/gepr/git/dotfiles-emacs-macros",
      "PATH": "/home/gepr/.local/bin:/home/gepr/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:~/.fzf/bin:/home/gepr/.fzf/bin",
      "PWD": "/home/gepr/git/site",
      "QT_IM_MODULE": "ibus",
      "SESSION_MANAGER": "local/unix:@/tmp/.ICE-unix/5259,unix/unix:/tmp/.ICE-unix/5259",
      "SHELL": "/bin/bash",
      "SHLVL": "3",
      "SSH_AGENT_PID": "5211",
      "SSH_AUTH_SOCK": "/tmp/ssh-XXXXXX856Yub/agent.5163",
      "SWAYSOCK": "/run/user/1000/sway-ipc.1000.8727.sock",
      "SYSTEMD_EXEC_PID": "5304",
      "TERM": "alacritty",
      "TERM_PROGRAM": "tmux",
      "TERM_PROGRAM_VERSION": "3.3a",
      "TMUX": "/tmp/tmux-1000/default,7111,0",
      "TMUX_PANE": "%4",
      "TMUX_PLUGIN_MANAGER_PATH": "/home/gepr/.config/tmux/plugins/",
      "USER": "gepr",
      "USERNAME": "gepr",
      "WAYLAND_DISPLAY": "wayland-1",
      "WINDOWID": "67108868",
      "WINDOWPATH": "2",
      "XAUTHORITY": "/run/user/1000/gdm/Xauthority",
      "XDG_CURRENT_DESKTOP": "GNOME",
      "XDG_DATA_DIRS": "/home/gepr/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/",
      "XDG_MENU_PREFIX": "gnome-",
      "XDG_RUNTIME_DIR": "/run/user/1000",
      "XDG_SESSION_CLASS": "user",
      "XDG_SESSION_DESKTOP": "gnome",
      "XDG_SESSION_TYPE": "x11",
      "XMODIFIERS": "@im=ibus",
      "_": "/usr/bin/python3"
    },
    "ansible_fibre_channel_wwn": [],
    "ansible_fips": false,
    "ansible_form_factor": "Notebook",
    "ansible_fqdn": "g5.local",
    "ansible_hostname": "g5",
    "ansible_hostnqn": "",
    "ansible_interfaces": [
      "wwp0s20f0u3c3",
      "wlp2s0",
      "lo",
      "tun0",
      "enp0s31f6"
    ],
    "ansible_is_chroot": false,
    "ansible_iscsi_iqn": "",
    "ansible_kernel": "6.3.12-100.fc37.x86_64",
    "ansible_kernel_version": "#1 SMP PREEMPT_DYNAMIC Wed Jul  5 20:09:58 UTC 2023",
    "ansible_lo": {
      "active": true,
      "device": "lo",
      "features": {
        "esp_hw_offload": "off [fixed]",
        "esp_tx_csum_hw_offload": "off [fixed]",
        "fcoe_mtu": "off [fixed]",
        "generic_receive_offload": "on",
        "generic_segmentation_offload": "on",
        "highdma": "on [fixed]",
        "hsr_dup_offload": "off [fixed]",
        "hsr_fwd_offload": "off [fixed]",
        "hsr_tag_ins_offload": "off [fixed]",
        "hsr_tag_rm_offload": "off [fixed]",
        "hw_tc_offload": "off [fixed]",
        "l2_fwd_offload": "off [fixed]",
        "large_receive_offload": "off [fixed]",
        "loopback": "on [fixed]",
        "macsec_hw_offload": "off [fixed]",
        "netns_local": "on [fixed]",
        "ntuple_filters": "off [fixed]",
        "receive_hashing": "off [fixed]",
        "rx_all": "off [fixed]",
        "rx_checksumming": "on [fixed]",
        "rx_fcs": "off [fixed]",
        "rx_gro_hw": "off [fixed]",
        "rx_gro_list": "off",
        "rx_udp_gro_forwarding": "off",
        "rx_udp_tunnel_port_offload": "off [fixed]",
        "rx_vlan_filter": "off [fixed]",
        "rx_vlan_offload": "off [fixed]",
        "rx_vlan_stag_filter": "off [fixed]",
        "rx_vlan_stag_hw_parse": "off [fixed]",
        "scatter_gather": "on",
        "tcp_segmentation_offload": "on",
        "tls_hw_record": "off [fixed]",
        "tls_hw_rx_offload": "off [fixed]",
        "tls_hw_tx_offload": "off [fixed]",
        "tx_checksum_fcoe_crc": "off [fixed]",
        "tx_checksum_ip_generic": "on [fixed]",
        "tx_checksum_ipv4": "off [fixed]",
        "tx_checksum_ipv6": "off [fixed]",
        "tx_checksum_sctp": "on [fixed]",
        "tx_checksumming": "on",
        "tx_esp_segmentation": "off [fixed]",
        "tx_fcoe_segmentation": "off [fixed]",
        "tx_gre_csum_segmentation": "off [fixed]",
        "tx_gre_segmentation": "off [fixed]",
        "tx_gso_list": "on",
        "tx_gso_partial": "off [fixed]",
        "tx_gso_robust": "off [fixed]",
        "tx_ipxip4_segmentation": "off [fixed]",
        "tx_ipxip6_segmentation": "off [fixed]",
        "tx_lockless": "on [fixed]",
        "tx_nocache_copy": "off [fixed]",
        "tx_scatter_gather": "on [fixed]",
        "tx_scatter_gather_fraglist": "on [fixed]",
        "tx_sctp_segmentation": "on",
        "tx_tcp6_segmentation": "on",
        "tx_tcp_ecn_segmentation": "on",
        "tx_tcp_mangleid_segmentation": "on",
        "tx_tcp_segmentation": "on",
        "tx_tunnel_remcsum_segmentation": "off [fixed]",
        "tx_udp_segmentation": "on",
        "tx_udp_tnl_csum_segmentation": "off [fixed]",
        "tx_udp_tnl_segmentation": "off [fixed]",
        "tx_vlan_offload": "off [fixed]",
        "tx_vlan_stag_hw_insert": "off [fixed]",
        "vlan_challenged": "on [fixed]"
      },
      "hw_timestamp_filters": [],
      "ipv4": {
        "address": "127.0.0.1",
        "broadcast": "",
        "netmask": "255.0.0.0",
        "network": "127.0.0.0",
        "prefix": "8"
      },
      "ipv6": [
        {
          "address": "::1",
          "prefix": "128",
          "scope": "host"
        }
      ],
      "mtu": 65536,
      "promisc": false,
      "timestamping": [],
      "type": "loopback"
    },
    "ansible_loadavg": {
      "15m": 0.44580078125,
      "1m": 0.25244140625,
      "5m": 0.3115234375
    },
    "ansible_local": {},
    "ansible_lsb": {},
    "ansible_lvm": "N/A",
    "ansible_machine": "x86_64",
    "ansible_machine_id": "43bad218515d473d90edf18c35cc826a",
    "ansible_memfree_mb": 16736,
    "ansible_memory_mb": {
      "nocache": {
        "free": 28418,
        "used": 2905
      },
      "real": {
        "free": 16736,
        "total": 31323,
        "used": 14587
      },
      "swap": {
        "cached": 0,
        "free": 8191,
        "total": 8191,
        "used": 0
      }
    },
    "ansible_memtotal_mb": 31323,
    "ansible_mounts": [
      {
        "block_available": 28446148,
        "block_size": 4096,
        "block_total": 123558144,
        "block_used": 95111996,
        "device": "/dev/mapper/luks-3ba07c47-486c-4025-bdbf-f40723721bf2",
        "fstype": "btrfs",
        "inode_available": 0,
        "inode_total": 0,
        "inode_used": 0,
        "mount": "/",
        "options": "rw,seclabel,relatime,compress=zstd:1,ssd,space_cache=v2,subvolid=1093,subvol=/thai23,bind",
        "size_available": 116515422208,
        "size_total": 506094157824,
        "uuid": "531f9d46-9f89-4571-b784-ace6e0f33d93"
      },
      {
        "block_available": 28446148,
        "block_size": 4096,
        "block_total": 123558144,
        "block_used": 95111996,
        "device": "/dev/mapper/luks-3ba07c47-486c-4025-bdbf-f40723721bf2",
        "fstype": "btrfs",
        "inode_available": 0,
        "inode_total": 0,
        "inode_used": 0,
        "mount": "/home",
        "options": "rw,seclabel,relatime,compress=zstd:1,ssd,space_cache=v2,subvolid=256,subvol=/home,bind",
        "size_available": 116515422208,
        "size_total": 506094157824,
        "uuid": "531f9d46-9f89-4571-b784-ace6e0f33d93"
      },
      {
        "block_available": 162028,
        "block_size": 4096,
        "block_total": 249195,
        "block_used": 87167,
        "device": "/dev/nvme0n1p2",
        "fstype": "ext4",
        "inode_available": 65438,
        "inode_total": 65536,
        "inode_used": 98,
        "mount": "/boot",
        "options": "rw,seclabel,relatime",
        "size_available": 663666688,
        "size_total": 1020702720,
        "uuid": "a60aec6f-6155-4d6a-bfed-55731f4fbef9"
      },
      {
        "block_available": 148847,
        "block_size": 4096,
        "block_total": 153296,
        "block_used": 4449,
        "device": "/dev/nvme0n1p1",
        "fstype": "vfat",
        "inode_available": 0,
        "inode_total": 0,
        "inode_used": 0,
        "mount": "/boot/efi",
        "options": "rw,relatime,fmask=0077,dmask=0077,codepage=437,iocharset=ascii,shortname=winnt,errors=remount-ro",
        "size_available": 609677312,
        "size_total": 627900416,
        "uuid": "5893-682A"
      }
    ],
    "ansible_nodename": "g5",
    "ansible_os_family": "RedHat",
    "ansible_pkg_mgr": "dnf",
    "ansible_proc_cmdline": {
      "BOOT_IMAGE": "(hd0,gpt2)/vmlinuz-6.3.12-100.fc37.x86_64",
      "quiet": true,
      "rd.luks.uuid": "luks-3ba07c47-486c-4025-bdbf-f40723721bf2",
      "rhgb": true,
      "ro": true,
      "root": "UUID=531f9d46-9f89-4571-b784-ace6e0f33d93",
      "rootflags": "subvol=thai23"
    },
    "ansible_processor": [
      "0",
      "GenuineIntel",
      "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
      "1",
      "GenuineIntel",
      "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
      "2",
      "GenuineIntel",
      "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
      "3",
      "GenuineIntel",
      "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
      "4",
      "GenuineIntel",
      "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
      "5",
      "GenuineIntel",
      "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
      "6",
      "GenuineIntel",
      "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz",
      "7",
      "GenuineIntel",
      "Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz"
    ],
    "ansible_processor_cores": 4,
    "ansible_processor_count": 1,
    "ansible_processor_nproc": 8,
    "ansible_processor_threads_per_core": 2,
    "ansible_processor_vcpus": 8,
    "ansible_product_name": "HP EliteBook 840 G5",
    "ansible_product_serial": "NA",
    "ansible_product_uuid": "NA",
    "ansible_product_version": "NA",
    "ansible_python": {
      "executable": "/usr/bin/python3",
      "has_sslcontext": true,
      "type": "cpython",
      "version": {
        "major": 3,
        "micro": 4,
        "minor": 11,
        "releaselevel": "final",
        "serial": 0
      },
      "version_info": [
        3,
        11,
        4,
        "final",
        0
      ]
    },
    "ansible_python_version": "3.11.4",
    "ansible_real_group_id": 1000,
    "ansible_real_user_id": 1000,
    "ansible_selinux": {
      "config_mode": "enforcing",
      "mode": "enforcing",
      "policyvers": 33,
      "status": "enabled",
      "type": "targeted"
    },
    "ansible_selinux_python_present": true,
    "ansible_service_mgr": "systemd",
    "ansible_ssh_host_key_ecdsa_public": "AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBHd9URBG8kt8PeluEVeRfvQh5swsTBdcc1HkJrHxGdjcN3GxqvUVznbc0Japv5ezj1ZEsfX7AXOPobWU/lsft5A=",
    "ansible_ssh_host_key_ecdsa_public_keytype": "ecdsa-sha2-nistp256",
    "ansible_ssh_host_key_ed25519_public": "AAAAC3NzaC1lZDI1NTE5AAAAIA+SdFDAbeCZZI1/x7VmbnZFvSHm5kofJ5/7CQq4J8Jz",
    "ansible_ssh_host_key_ed25519_public_keytype": "ssh-ed25519",
    "ansible_ssh_host_key_rsa_public": "AAAAB3NzaC1yc2EAAAADAQABAAABgQCRjbJgZUvFpaotmoER2iGfFcLqLvFc49sp5VP8MIVQXx1hu8wzibAKn0If4YBNCxAFSngVNbqv0hhbYkm6+NLO9Xxn0e/3D/KMwq4d4q4jXKlpNV+oHsOPPHI8PVHdnbcGlhprIj+9sc9oGl1Adf/nVFmkt1z3z/60N9EQFyve1IAfT4bk2KA5G3SFrwI8D7T/KpbsrMOr2/ofUS8GWujezMY5Rc/Hif1va3kuu1eln/Fu4p//NwtejfRAN/sp5WScorHPUqY6o/OgRxJbWoWmqiQx+oHZL2Z3JxXJ7SgTAz5fwiX7A61coVibN/bo3EdvUn4cO46uhQ1vTzDkYif8XAhwMaJM0LkqIdca+NrkYXecxK7TsuBEGP/UAvoLDGgntlEVAvfLi4oiYJlLesg7q1MWH7Db6t24hI32G9vhQj3bjoMSdzLDwPTObbwgz+aDhdUcJEykzq6LAzvp1eFe0GxjgaIh3UnFFNBd7GiwR3Va2Q668d42G3wpB6fH4eE=",
    "ansible_ssh_host_key_rsa_public_keytype": "ssh-rsa",
    "ansible_swapfree_mb": 8191,
    "ansible_swaptotal_mb": 8191,
    "ansible_system": "Linux",
    "ansible_system_capabilities": [
      ""
    ],
    "ansible_system_capabilities_enforced": "True",
    "ansible_system_vendor": "HP",
    "ansible_tun0": {
      "active": true,
      "device": "tun0",
      "features": {
        "esp_hw_offload": "off [fixed]",
        "esp_tx_csum_hw_offload": "off [fixed]",
        "fcoe_mtu": "off [fixed]",
        "generic_receive_offload": "on",
        "generic_segmentation_offload": "on",
        "highdma": "off [fixed]",
        "hsr_dup_offload": "off [fixed]",
        "hsr_fwd_offload": "off [fixed]",
        "hsr_tag_ins_offload": "off [fixed]",
        "hsr_tag_rm_offload": "off [fixed]",
        "hw_tc_offload": "off [fixed]",
        "l2_fwd_offload": "off [fixed]",
        "large_receive_offload": "off [fixed]",
        "loopback": "off [fixed]",
        "macsec_hw_offload": "off [fixed]",
        "netns_local": "off [fixed]",
        "ntuple_filters": "off [fixed]",
        "receive_hashing": "off [fixed]",
        "rx_all": "off [fixed]",
        "rx_checksumming": "off [fixed]",
        "rx_fcs": "off [fixed]",
        "rx_gro_hw": "off [fixed]",
        "rx_gro_list": "off",
        "rx_udp_gro_forwarding": "off",
        "rx_udp_tunnel_port_offload": "off [fixed]",
        "rx_vlan_filter": "off [fixed]",
        "rx_vlan_offload": "off [fixed]",
        "rx_vlan_stag_filter": "off [fixed]",
        "rx_vlan_stag_hw_parse": "off [fixed]",
        "scatter_gather": "on",
        "tcp_segmentation_offload": "off",
        "tls_hw_record": "off [fixed]",
        "tls_hw_rx_offload": "off [fixed]",
        "tls_hw_tx_offload": "off [fixed]",
        "tx_checksum_fcoe_crc": "off [fixed]",
        "tx_checksum_ip_generic": "off [requested on]",
        "tx_checksum_ipv4": "off [fixed]",
        "tx_checksum_ipv6": "off [fixed]",
        "tx_checksum_sctp": "off [fixed]",
        "tx_checksumming": "off",
        "tx_esp_segmentation": "off [fixed]",
        "tx_fcoe_segmentation": "off [fixed]",
        "tx_gre_csum_segmentation": "off [fixed]",
        "tx_gre_segmentation": "off [fixed]",
        "tx_gso_list": "off [fixed]",
        "tx_gso_partial": "off [fixed]",
        "tx_gso_robust": "off [fixed]",
        "tx_ipxip4_segmentation": "off [fixed]",
        "tx_ipxip6_segmentation": "off [fixed]",
        "tx_lockless": "on [fixed]",
        "tx_nocache_copy": "off",
        "tx_scatter_gather": "on",
        "tx_scatter_gather_fraglist": "on",
        "tx_sctp_segmentation": "off [fixed]",
        "tx_tcp6_segmentation": "off [requested on]",
        "tx_tcp_ecn_segmentation": "off [requested on]",
        "tx_tcp_mangleid_segmentation": "off",
        "tx_tcp_segmentation": "off [requested on]",
        "tx_tunnel_remcsum_segmentation": "off [fixed]",
        "tx_udp_segmentation": "off [requested on]",
        "tx_udp_tnl_csum_segmentation": "off [fixed]",
        "tx_udp_tnl_segmentation": "off [fixed]",
        "tx_vlan_offload": "on",
        "tx_vlan_stag_hw_insert": "on",
        "vlan_challenged": "off [fixed]"
      },
      "hw_timestamp_filters": [],
      "ipv4": {
        "address": "10.4.11.195",
        "broadcast": "",
        "netmask": "255.255.255.0",
        "network": "10.4.11.0",
        "prefix": "24"
      },
      "ipv6": [
        {
          "address": "fe80::974c:10ec:a6b5:2ab7",
          "prefix": "64",
          "scope": "link"
        }
      ],
      "mtu": 1419,
      "promisc": false,
      "speed": 10000,
      "timestamping": [],
      "type": "tunnel"
    },
    "ansible_uptime_seconds": 70521,
    "ansible_user_dir": "/home/gepr",
    "ansible_user_gecos": "gepr",
    "ansible_user_gid": 1000,
    "ansible_user_id": "gepr",
    "ansible_user_shell": "/bin/bash",
    "ansible_user_uid": 1000,
    "ansible_userspace_architecture": "x86_64",
    "ansible_userspace_bits": "64",
    "ansible_virtualization_role": "host",
    "ansible_virtualization_tech_guest": [],
    "ansible_virtualization_tech_host": [
      "kvm"
    ],
    "ansible_virtualization_type": "kvm",
    "ansible_wlp2s0": {
      "active": true,
      "device": "wlp2s0",
      "features": {
        "esp_hw_offload": "off [fixed]",
        "esp_tx_csum_hw_offload": "off [fixed]",
        "fcoe_mtu": "off [fixed]",
        "generic_receive_offload": "on",
        "generic_segmentation_offload": "on",
        "highdma": "on",
        "hsr_dup_offload": "off [fixed]",
        "hsr_fwd_offload": "off [fixed]",
        "hsr_tag_ins_offload": "off [fixed]",
        "hsr_tag_rm_offload": "off [fixed]",
        "hw_tc_offload": "off [fixed]",
        "l2_fwd_offload": "off [fixed]",
        "large_receive_offload": "off [fixed]",
        "loopback": "off [fixed]",
        "macsec_hw_offload": "off [fixed]",
        "netns_local": "on [fixed]",
        "ntuple_filters": "off [fixed]",
        "receive_hashing": "off [fixed]",
        "rx_all": "off [fixed]",
        "rx_checksumming": "off [fixed]",
        "rx_fcs": "off [fixed]",
        "rx_gro_hw": "off [fixed]",
        "rx_gro_list": "off",
        "rx_udp_gro_forwarding": "off",
        "rx_udp_tunnel_port_offload": "off [fixed]",
        "rx_vlan_filter": "off [fixed]",
        "rx_vlan_offload": "off [fixed]",
        "rx_vlan_stag_filter": "off [fixed]",
        "rx_vlan_stag_hw_parse": "off [fixed]",
        "scatter_gather": "on",
        "tcp_segmentation_offload": "off",
        "tls_hw_record": "off [fixed]",
        "tls_hw_rx_offload": "off [fixed]",
        "tls_hw_tx_offload": "off [fixed]",
        "tx_checksum_fcoe_crc": "off [fixed]",
        "tx_checksum_ip_generic": "off [fixed]",
        "tx_checksum_ipv4": "off [fixed]",
        "tx_checksum_ipv6": "off [fixed]",
        "tx_checksum_sctp": "off [fixed]",
        "tx_checksumming": "off",
        "tx_esp_segmentation": "off [fixed]",
        "tx_fcoe_segmentation": "off [fixed]",
        "tx_gre_csum_segmentation": "off [fixed]",
        "tx_gre_segmentation": "off [fixed]",
        "tx_gso_list": "off [fixed]",
        "tx_gso_partial": "off [fixed]",
        "tx_gso_robust": "off [fixed]",
        "tx_ipxip4_segmentation": "off [fixed]",
        "tx_ipxip6_segmentation": "off [fixed]",
        "tx_lockless": "off [fixed]",
        "tx_nocache_copy": "off",
        "tx_scatter_gather": "on",
        "tx_scatter_gather_fraglist": "off [fixed]",
        "tx_sctp_segmentation": "off [fixed]",
        "tx_tcp6_segmentation": "off [fixed]",
        "tx_tcp_ecn_segmentation": "off [fixed]",
        "tx_tcp_mangleid_segmentation": "off [fixed]",
        "tx_tcp_segmentation": "off [fixed]",
        "tx_tunnel_remcsum_segmentation": "off [fixed]",
        "tx_udp_segmentation": "off [fixed]",
        "tx_udp_tnl_csum_segmentation": "off [fixed]",
        "tx_udp_tnl_segmentation": "off [fixed]",
        "tx_vlan_offload": "off [fixed]",
        "tx_vlan_stag_hw_insert": "off [fixed]",
        "vlan_challenged": "off [fixed]"
      },
      "hw_timestamp_filters": [],
      "ipv4": {
        "address": "10.0.10.201",
        "broadcast": "10.0.10.255",
        "netmask": "255.255.255.0",
        "network": "10.0.10.0",
        "prefix": "24"
      },
      "ipv6": [
        {
          "address": "fe80::ccef:1f23:7dbb:8288",
          "prefix": "64",
          "scope": "link"
        }
      ],
      "macaddress": "3c:6a:a7:c3:ff:78",
      "module": "iwlwifi",
      "mtu": 1500,
      "pciid": "0000:02:00.0",
      "promisc": false,
      "timestamping": [],
      "type": "ether"
    },
    "ansible_wwp0s20f0u3c3": {
      "active": false,
      "device": "wwp0s20f0u3c3",
      "features": {
        "esp_hw_offload": "off [fixed]",
        "esp_tx_csum_hw_offload": "off [fixed]",
        "fcoe_mtu": "off [fixed]",
        "generic_receive_offload": "on",
        "generic_segmentation_offload": "off [requested on]",
        "highdma": "off [fixed]",
        "hsr_dup_offload": "off [fixed]",
        "hsr_fwd_offload": "off [fixed]",
        "hsr_tag_ins_offload": "off [fixed]",
        "hsr_tag_rm_offload": "off [fixed]",
        "hw_tc_offload": "off [fixed]",
        "l2_fwd_offload": "off [fixed]",
        "large_receive_offload": "off [fixed]",
        "loopback": "off [fixed]",
        "macsec_hw_offload": "off [fixed]",
        "netns_local": "off [fixed]",
        "ntuple_filters": "off [fixed]",
        "receive_hashing": "off [fixed]",
        "rx_all": "off [fixed]",
        "rx_checksumming": "off [fixed]",
        "rx_fcs": "off [fixed]",
        "rx_gro_hw": "off [fixed]",
        "rx_gro_list": "off",
        "rx_udp_gro_forwarding": "off",
        "rx_udp_tunnel_port_offload": "off [fixed]",
        "rx_vlan_filter": "on [fixed]",
        "rx_vlan_offload": "off [fixed]",
        "rx_vlan_stag_filter": "off [fixed]",
        "rx_vlan_stag_hw_parse": "off [fixed]",
        "scatter_gather": "off",
        "tcp_segmentation_offload": "off",
        "tls_hw_record": "off [fixed]",
        "tls_hw_rx_offload": "off [fixed]",
        "tls_hw_tx_offload": "off [fixed]",
        "tx_checksum_fcoe_crc": "off [fixed]",
        "tx_checksum_ip_generic": "off [fixed]",
        "tx_checksum_ipv4": "off [fixed]",
        "tx_checksum_ipv6": "off [fixed]",
        "tx_checksum_sctp": "off [fixed]",
        "tx_checksumming": "off",
        "tx_esp_segmentation": "off [fixed]",
        "tx_fcoe_segmentation": "off [fixed]",
        "tx_gre_csum_segmentation": "off [fixed]",
        "tx_gre_segmentation": "off [fixed]",
        "tx_gso_list": "off [fixed]",
        "tx_gso_partial": "off [fixed]",
        "tx_gso_robust": "off [fixed]",
        "tx_ipxip4_segmentation": "off [fixed]",
        "tx_ipxip6_segmentation": "off [fixed]",
        "tx_lockless": "off [fixed]",
        "tx_nocache_copy": "off",
        "tx_scatter_gather": "off [fixed]",
        "tx_scatter_gather_fraglist": "off [fixed]",
        "tx_sctp_segmentation": "off [fixed]",
        "tx_tcp6_segmentation": "off [fixed]",
        "tx_tcp_ecn_segmentation": "off [fixed]",
        "tx_tcp_mangleid_segmentation": "off [fixed]",
        "tx_tcp_segmentation": "off [fixed]",
        "tx_tunnel_remcsum_segmentation": "off [fixed]",
        "tx_udp_segmentation": "off [fixed]",
        "tx_udp_tnl_csum_segmentation": "off [fixed]",
        "tx_udp_tnl_segmentation": "off [fixed]",
        "tx_vlan_offload": "on [fixed]",
        "tx_vlan_stag_hw_insert": "off [fixed]",
        "vlan_challenged": "off [fixed]"
      },
      "hw_timestamp_filters": [],
      "macaddress": "d2:a8:57:dc:5e:80",
      "module": "cdc_mbim",
      "mtu": 1500,
      "pciid": "1-3:3.0",
      "promisc": false,
      "timestamping": [],
      "type": "ether"
    },
    "gather_subset": [
      "all"
    ],
    "module_setup": true
  },
  "changed": false
}
